const recettes = [
    {
    "description" : "Du vrai praliné, on peut le faire seulement avec des noisettes.",
    "difficulte" : "facile",
    "image" : "http://2.bp.blogspot.com/-ohDafYZdUkQ/UW6SD9wGmyI/AAAAAAAABcE/RYm4XbJSW6w/s1600/Praline_maison_recette.jpg",
    "ingredients" : "125 g de noisettes, 125 g d'amende, 60 g de sucre, 5 cl d'eau",
    "instructions" : "Faire torréfier le fruits sec au four à 150° (T 5)\nCuire le sucre dans une poêle avec l'eau\nUne fois la température du sucre à 118°, ajouter les fruits sec\nLaisser cuire à feu moyen jusqu'à la caramélisation",
    "nom" : "Praliné maison",
    "tempsCuisson" : "25mn",
    "tempsPreparation" : "15mn",
    "video" : "https://www.youtube.com/watch?v=i1BGr_xjI-Y",
    "categorie":"preparation"
  }, 
  {
    "description" : "Une bonne base pour créer des crèmes patissière au chocolat, praliné etc ...",
    "image" : "http://icu.linter.fr/750/10001783/1827534364/creme-patissiere.jpg",
    "ingredients" : "1/2 litre de lait,100 g de sucre,4 jaunes d'oeufs, 60 g de Maïzena,1 gousse de vanille",
    "instructions" : "Fendez la gousse de vanille en deux, sur sa longueur et avec le dos d'une lame de couteau, grattez l'intérieur de la gousse pour en extraire les grains de vanille.\nDans une grande casserole, versez le lait, ajoutez les grains de vanille et la moitié du sucre. Ne remuez pas et faîtes chauffer le tout sur feu moyen, jusqu'à ébullition.\nDans un saladier, versez les jaunes d'oeuf et le reste de sucre. Blanchissez le mélange à l'aide d'un fouet, pour obtenir une préparation mousseuse. Ajoutez la Maïzena et mélangez.\nVersez le lait chaud, petit à petit sur les jaunes d'oeuf, tout en mélangeant.\nHors du feu, versez la préparation dans la casserole et laissez le temps à l'amidon d'absorber le lait. L'amidon va absorber six fois son temps.\nUne fois que la préparation a bien gonflé, placez-la sur le feu pour le porter à ébullition 1 à 2 min, sans cesser de remuer énergiquement pour ne pas qu'elle colle à la casserole. La crème doit épaissir et se tenir.\nA la fin de cuisson, ajoutez une pincée de sel, qui est un exhausteur de goût. Vous pouvez également ajouter une noix de beurre pour plus de gourmandise.\nFilmez la crème pâtissière au contact, c'est à dire que le film alimentaire doit toucher la crème pour ne pas qu'elle croûte.\nLaissez la refroidir une bonne heure au frigo, avant de l'utiliser pour garnir un gateau.",
    "nom" : "Crème pâtissière",
    "categorie":"preparation"
  },
   {
    "description" : "Recette au Cooking Chef Premium : la pâte à choux par l'Atelier des Chefs ",
    "difficulte" : "facile",
    "image" : "https://files.meilleurduchef.com/mdc/photo/recette/pate-a-choux/pate-a-choux-640.jpg",
    "ingredients" : "100 g de beurre, 25 cl d'eau, 1 pincée de sel, 2 pincées de sucre, 150 g de farine, 4 oeufs",
    "instructions" : "Mettre l'eau, le beurre, le sel et le sucre dans le bol du robot. Installer le batteur souple et régler la température au maximum, le minuteur sur 4 min et la vitesse sur « Mélange 1 ».\nAjouter la farine dans le bol du robot et appuyer sur la touche « P » pendant 10 s. Répéter l'opération 3 fois pour bien mélanger la farine.\nRégler la température sur 70 °C, le minuteur sur 2 min et la vitesse sur « Mélange 1 » pour dessécher la pâte. Arrêter la cuisson, régler le minuteur sur 3 min et la vitesse sur « Minimum ».\nLaisser ensuite la pâte refroidir jusqu'à ce qu'elle descende en dessous de 60 °C.\nRégler la vitesse sur 2 et ajouter les oeufs un par un, en attendant que chaque oeuf soit bien incorporé avant d'ajouter le suivant.\nArrêter ensuite le robot et transférer la pâte dans une poche à douille munie d'une douille.",
    "nom" : "Pâte à choux (Cooking Chef)",
    "tempsCuisson" : "5mn",
    "tempsPreparation" : "10mn",
    "video" : "https://www.youtube.com/watch?v=WGFBihG1dpU",
    "categorie":"preparation"
  },
   {
    "description" : "Un fondant plein de générosité et de gourmandise. Retrouvez la recette en Live sur la page facebook du Chef, où il partage avec vous, toutes les clés et astuces.",
    "difficulte" : "facile",
    "image" : "http://www.conticini.fr/wp-content/uploads/2016/04/fondant.jpg",
    "ingredients" : "65 g de sucre,58 g de farine T45,120 g d'oeuf battu,115 g de beurre,95 g de chocolat noir,20 g de chocolat au lait,20 g de chocolat blanc concassé,1 pincée de fleur de sel",
    "instructions" : "Faites fondre les chocolats au bain-marie avec le beurre.\nDans un saladier, mélangez les œufs, le sucre et la farine préalablement tamisée à l’aide d’un fouet.\nVersez ensuite sur les œufs, le chocolat fondu avec le beurre en une fois, mélangez le tout très rapidement à l’aide d’un fouet pour ne pas que le mélange tranche.\nBeurrez et farinez un cercle de 14 cm de diamètre et 3.5 cm de hauteur, puis coulez l’appareil dans les cercles, à mis hauteur.\nParsemez le centre de brisure de chocolat blanc, parsemez de quelque grain de fleur de sel, puis coulez à nouveau de l’appareil jusqu’au 2/3 de la hauteur du cercle.\nCuire le gâteau 10 min dans un four à 170°C.",
    "nom" : "Fondant ultra fondant au chocolat",
    "tempsCuisson" : "10mn",
    "tempsPreparation" : "15mn",
    "video" : "https://www.youtube.com/watch?v=S6zOnt9dY3g",
    "categorie":"patisserie"
  },
  {
    "description" : "La crème aux oeufs de notre enfance, pleine de douceur lactée, au bon goût de caramel. Pour 6 personnes",
    "difficulte" : "facile",
    "image" : "http://www.conticini.fr/wp-content/uploads/2016/03/creme-caramel.jpg",
    "ingredients" : "250 g de sucre (caramel),1L de lait,5 petits oeufs ou 4 gros (200g),3 jaunes d'oeufs (60 g),150 g sucre,2 gousses de vanille",
    "instructions" : "Pour le caramel\nFaites chauffer une petite casserole , à feu moyen, puis, versez, petit à petit, le sucre semoule à sec,en 2 ou 3 fois sans jamais cesser de mélanger le sucre caramélisé à l’aide d’une cuillère en bois.\nQuand le caramel prend une couleur auburn (blond foncé),et avant qu’il ne fume, le caramel est prêt.\nLaissez refroidir le caramel à température ambiante pendant 2 mn, puis versez-le dans 6 ramequins, pour en tapisser le fond.\nDans un saladier, mélangez le sucre, les œufs, les jaunes d’œufs et la gousse de vanille préalablement fendue et grattée. Fouettez le tout au fouet, jusqu’à ce que le mélange blanchisse.\nAjoutez le lait froid, puis fouettez à nouveau.\nLaissez reposer le tout pendant quelques minutes pour éliminer les bulles d’air qui se sont formées à la surface de la crème.\nVersez la crème aux œufs dans les ramequins à hauteur, puis faites-les cuire au bain marie sur une grille (et non une plaque). \nPour cela, déposez les ramequins dans un plat à gratin dont vous aurez préalablement rempli le fond avec de l’eau froide, puis recouvrez la surface des ramequins d’une feuille de papier aluminium en surface.\nFaites cuire au four à 120° (130° pour les fours ménagers), pendant 2 heures.",
    "nom" : "Crème aux oeufs",
    "tempsCuisson" : "2h10",
    "tempsPreparation" : "30mn",
    "categorie":"patisserie"
  },
   {
    "description" : "Une douce ganache au chocolat noir et au chocolat au lait, moelleuse et fondante, sur un fond de pâte sucrée. Divin !",
    "difficulte" : "facile",
    "image" : "http://www.conticini.fr/wp-content/uploads/2016/03/12545281_1560436810948174_1925552213_n.jpg",
    "ingredients" : "200 g de pâte sucré,170 g de chocolat noir,30 g de chocolat au lait,150 g de lait demi écrémé,150 g de crème liquide,1 oeuf (50 g)",
    "instructions" : "Dans une casserole, portez à ébullition le lait et la crème.\nDans un saladier, versez, en deux fois, le lait et la crème bouillant, sur les deux chocolats préalablement hachés finement au couteau.\nQuand le chocolat est entièrement fondu, incorporez l’œuf entier et mélangez. La ganache est semi-liquide.\nVersez la ganache chocolat dans le fond de pâte sucrée déjà cuit, jusqu’à un demi-centimètre du bord.\nFaites cuire le tout au four à 150°, pendant 15 à 20 min selon les fours.\nLa tarte est prête à déguster quand la ganache est tremblotante. Si elle est encore trop liquide, c’est qu’elle n’est pas assez cuite. Si elle est trop compacte, c’est qu’elle est trop cuite.\nLaissez tiédir la tarte à température ambiante et dégustez-la tiède.",
    "nom" : "Tarte au chocolat",
    "tempsCuisson" : "15mn",
    "tempsPreparation" : "20mn",
    "video" : "https://www.youtube.com/watch?v=1b99rSw2g_0&t=80s",
    "categorie":"patisserie"
  },
   {
    "description" : "Préparation de base pour fond de tarte. Recette pour 500g.",
    "difficulte" : "facile",
    "image" : "http://www.lacuisinedethomas.fr/wp-content/uploads/2014/04/pate_sucree.jpg",
    "ingredients" : "230 g de farine, 140 g de beurre, 1 oeuf entier (50 g),1 jaune d'oeuf (20 g),90 g de sucre glace,40 g de poudre d'amende,4 pincées de sel fin,les zestes d'un citron,1 demi-gousse de vanille",
    "instructions" : "Dans le bol d’un robot, pétrissez, à vitesse lente, le beurre pommade (sorti préalablement du réfrigérateur 1h30 avant) à l’aide d’une « feuille » (accessoire du robot), puis crémez-le, en incorporant le sucre glace, de manière à obtenir une texture crémeuse.\nAjoutez les zestes de citron, puis la poudre d’amande. Fouettez de nouveau, en veillant à bien racler les parois du bol pour bien ramener la pâte vers le centre de la cuve.\nAjoutez alors l’œuf, le jaune d’œuf, la vanille réduite en poudre, puis la farine et le sel préalablement mélangés.\nAttention : à partir du moment où vous avez incorporé la farine, le mélange doit se faire en deux fois et très rapidement.\nTerminez en déposant la pâte sur votre plan de travail, puis en l’étalant avec la paume de votre main en trois ou quatre ultimes mouvements.\nCouvrez avec du film alimentaire, puis mettez le tout au réfrigérateur pendant trois ou quatre heures afin de que se développent un maximum d’arômes.",
    "nom" : "Pâte sucrée",
    "tempsCuisson" : "15mn",
    "tempsPreparation" : "20mn",
    "video" : "https://www.youtube.com/watch?v=Eqh7bBzf7D0",
    "categorie":"preparation"
  },
   {
    "description" : "La sauce blanche par excellence, simple et goûteuse. Une base idéale pour beaucoup de plats du quotidien. ",
    "difficulte" : "facile",
    "image" : "http://static.cuisineaz.com/610x610/i108153-sauce-bechamel.jpg",
    "ingredients" : "50 g de farine,50 g de beurre,60 cl de lait,sel,poivre,noix de muscade",
    "instructions" : "Faites fondre le beurre dans une casserole à fond épais.\nAjoutez la farine et remuez avec une cuillère de bois sans laisser colorer. La farine doit juste épaissir.\nVersez le lait progressivement, sans cesser de remuer, jusqu'à ce que la sauce épaississe.\nAssaisonnez de sel, poivre et muscade râpée. ",
    "nom" : "Sauce bechamel",
    "tempsCuisson" : "10mn",
    "tempsPreparation" : "10mn",
    "video" : "",
    "categorie":"preparation"
  },
   {
    "description" : "La recette de Philippe Conticini.",
    "difficulte" : "facile",
    "image" : "http://static.750g.com/images/622-auto/d93849d60459865d3949572ecadb7c09/mousse-au-chocolat-de-philippe-conticini.jpg",
    "ingredients" : "230 g de chocolat, 70 g de lait demi écrémé,150 g de crème fraîche liquide,35 g de sucre roux,7 blancs d’œufs,1 pincée de fleur de sel ",
    "instructions" : "Faites fondre la chocolat noir au bain-marie.\nDans une casserole, portez à ébullition le lait et la crème puis verser le liquide en trois fois sur le chocolat, tout en mélangeant avec un fouet.\nLaissez tiédir le mélange chocolat/lait dans un cul de poule (idéalement à 40°C).\nPendant ce temps, montez les blancs d'œufs. Dans le bol de votre robot, placez le sucre roux et versez les blancs d'oeuf. Battez les blancs à vitesse moyenne. Lorsqu'ils deviennent mousseux, serrez-les en mettant le fouet à vitesse maximum une quinzaine de secondes.\nIncorporez délicatement un tiers des blancs montés à la ganache, avec un fouet à main. Mélangez.\nAjoutez délicatement le reste des blancs en neige à la préparation, à l'aide d'une maryse. Cassez délicatement les blancs en neige pour qu'ils s'incorporent totalement à la ganache.\nLaissez reposer la mousse au chocolat au frais, au minimum 2 heures.\nAu moment de servir, ajoutez quelques cristaux de fleur de sel.",
    "nom" : "Mousse au chocolat",
    "tempsCuisson" : "",
    "tempsPreparation" : "10mn",
    "video" : "https://www.youtube.com/watch?v=jv3CzrQD-vg",
    "categorie":"patisserie"
  },
   {
    "description" : "Le véritable cookie américain, chez vous, dans votre cuisine !",
    "difficulte" : "facile",
    "image" : "http://static.750g.com/images/auto-427/57478fe6c5b8f9f0402683d343bb09de/veritables-cookies-americains.jpg",
    "ingredients" : "100 g de pépite de chocolat,1 pincée de sel,1 sachet de sucre vanillé,150 g de cassonade,1cc de levure chimique,1 oeuf,125 g de beurre,250 g de farine",
    "instructions" : "Mélanger la farine, le sel, l'oeuf et la levure chimique.\nAjouter le beurre fondu, les sucres et le Rajouter les pépites de chocolat dans la pâte.\nFormer des boulettes dans sa main de la taille d'une grosse noix et les disposer bien espacés sur une plaque de cuisson.\nEnfourner à 150/160° pendant une dizaine de minutes.",
    "nom" : "Cookies à l'amricaine",
    "tempsCuisson" : "10mn",
    "tempsPreparation" : "10mn",
    "video" : "",
    "categorie":"patisserie"
  },
   {
    "description" : "Cette recette est géniale et les brownies sont chocolatés, fondants avec une croûte craquante...",
    "difficulte" : "facile",
    "image" : "http://static.750g.com/images/auto-427/1c4fb3b9d3412dd1bcd311d72ff815e0/brownies-intenses-et-fondants.jpg",
    "ingredients" : "1cc de levure, quelques noix de pecan,sel,vanille liquide,37 g de farine,2 œufs,80 g de sucre,100 g de beurre,130 g de chocolat ",
    "instructions" : "Faire fondre le chocolat, puis ajouter le beurre. Laisser fondre.\nAjouter le sucre puis les oeufs battus, et enfin la farine, la levure, la vanille, le sel et les noix.\nEnfourner dans un petit plat carré, 20 minutes à 180 °C. Moi je l'ai fait cuire 10 minutes à 180°C puis 10 minutes à 160 °C pour qu'il soit un peu coulant.",
    "nom" : "Brownies",
    "tempsCuisson" : "20mn",
    "tempsPreparation" : "15mn",
    "video" : "",
    "categorie":"patisserie"
  },
   {
    "description" : "Parfaits pour un petit-déjeuner maison...",
    "difficulte" : "facile",
    "image" : "https://files.meilleurduchef.com/mdc/photo/recette/pancake/pancake-1200.jpg",
    "ingredients" : "4 œufs,30 cl de lait,250g de farine,2 c à c de levure chimique,4 c à s de sucre, 2 pincées de sel,Huile",
    "instructions" : "Séparez les blancs des jaunes. Mélangez les jaunes avec le lait. Ajoutez le sucre, la farine, la levure, le sel et mélangez, jusqu’à obtenir une pâte lisse. Battez les blancs en neige, puis incorporez-les à la pâte. \nFaites chauffer et graissez une poêle avec un peu d’huile. Déposez 2 à 3 petites louches de pâte dans la poêle en les espaçant. Dès qu’une multitude de petites bulles apparaissent à la surface des pancakes, retournez-les. Poursuivez la cuisson pendant encore un peu moins d’1 minute. \nDéposez-les sur une assiette puis poursuivez la cuisson jusqu’à épuisement de la pâte. Servez chaud avec du sirop d’érable et des noix de pécan.",
    "nom" : "Pancakes",
    "tempsCuisson" : "5mn",
    "tempsPreparation" : "10mn",
    "video" : "http://video.750g.com/16/07/12/15/25158_hd_013.mp4",
    "categorie":"patisserie"
  },
   {
    "description" : "La recette de la pâte à crêpes !",
    "difficulte" : "facile",
    "image" : "http://static.750g.com/images/622-auto/6d843ee0f59336a2804a2fd32d7ad620/pate-a-crepes.png",
    "ingredients" : "1 zeste de citron, 1 zeste d'orange,2cs de fleur d'oranger (facultatif),50g de beurre fondu,1 pincée de sel,50cl de lait, 3 oeufs, 250g de farine",
    "instructions" : "Tiédir le beurre.\nMettre dans un saladier la farine et le sel.\nCasser les œufs et les poser sur la farine et les zestes.\nVerser l'intégralité du lait et du beurre fondu (et le fleur d'oranger).\nFouetter doucement en évitant la formation de grumeaux.\nLaisser reposer 30 minutes. \nDétendre avec un peu d'eau ou de bierre si nécessaire.",
    "nom" : "Pâte à crêpes",
    "tempsCuisson" : "20mn",
    "tempsPreparation" : "10mn",
    "video" : "",
    "categorie":"preparation"
  },
   {
    "description" : "Une préparation composée de sirop de sucre concentré et de jaunes d’œufs que l’on utilise comme base pour créer des entremets (trianon etc ...)",
    "difficulte" : "facile",
    "image" : "https://www.papillesetpupilles.fr/wp-content/uploads/2012/02/Mousse-au-chocolat.jpg",
    "ingredients" : "50 ml d’eau,150 g de sucre en poudre,200 g de chocolat noir,200 ml de crème liquide,3 jaunes d’œufs,1 oeuf",
    "instructions" : "Préparation du sirop : Versez dans une casserole 50 ml d’eau + 80 g de sucre. Faites chauffer jusqu’à ce que la température de cette préparation atteigne 121°C.\nfaire fondre 200g de chocolat au bain marie et fouettez la crème au batteur.\nDans le bol du robot, mettez les 3 jaunes d’oeufs et l’œuf, ajoutez 80g de sucre en poudre et fouettez jusqu’à ce que le mélange blanchisse.\nQuand le sirop a atteint la bonne température, versez-le sur le mélange œuf/sucre en continuant de battre et en versant doucement.\nContinuez à fouettez jusqu’à ce que le mélange ait complètement refroidi.\nAjoutez ensuite le chocolat fondu en continuant de battre puis stop. Prenez la crème montée et incorporez-la délicatement en deux fois au mélange à base de chocolat.",
    "nom" : "Pâte à bombe au chocolat",
    "tempsCuisson" : "",
    "tempsPreparation" : "30mn",
    "video" : "",
    "categorie":"preparation"
  },
  {
    "description" : "Un cake sublime pour les amoureux de chocolat… J’avais ma recette de cake chocolat de je ne sais ou, que j’ai remplacé après avoir essayé cette recette de Conticini, car elle est parfaitement équilibrée, forte en chocolat tout en restant fine en bouche. (Pour un moule de 27 cm)",
    "difficulte" : "facile",
    "image" : "http://www.cuisinedaubery.com/wp-content/uploads/2017/06/cake-chocolat-bigbanner.png",
    "ingredients" : "60 g de chocolat noir, 30 g de chocolat au lait,105 g de beurre salé, 112 g de sucre roux,135 g de poudre de noisettes,30 g de jaunes d’œuf,75 g d’œufs,30 g de crème liquide,1 pincée de sel,60 g de farine, 1 cuillère à café de levure chimique,105 g de chocolat noir (pépites),135 g de blancs d’œuf.",
    "instructions" : "Faire fondre au bain-marie le chocolat Noir, le chocolat au lait, le beurre salé.\nMélanger le sucre roux et la poudre de noisettes.\nAjouter les jaunes d’œufs et mélanger à la spatule.\nAjouter les chocolats fondus et mélanger.\nVerser la crème liquide et mélanger.\nTamiser au dessus du mélange le sel, la farine et la levure puis mélanger à la spatule.\nConcasser les 105 g de chocolat pour le pépites puis mélanger à la pâte.\nFaire mousser les blancs d’œufs (à température ambiante) puis les incorporer doucement à la préparation.\nFaire chauffer le four à 180°C (T 6) et enfourner pour 40 mn.\nAu bout de 20 ou 25 mn entailler le cake sur la longueur à l'aide d'un couteau.",
    "nom" : "Le Cake Sublime Chocolat de Conticini",
    "tempsCuisson" : "40 mn",
    "tempsPreparation" : "30 mn",
    "video" : "",
    "categorie":"patisserie"
  },
  {
    "description" : "Super pâte à choux pour le cooking chef",
    "difficulte" : "facile",
    "image" : "https://www.cooking-chef.fr/sites/default/files/styles/recipe_visuel_node/public/recettes/pate_a_choux.jpg?itok=Qz0iIfud",
    "ingredients" : "160 g de lait, 160 g d'eau, 5 g de sucre, 5 g de sel, 150 g de beurre, 180 g de farine, 5 oeufs",
    "instructions" : "Tamiser la farine, et sortir les œufs du réfrigérateur pour qu’ils soient à température ambiante.\nMettre le lait, l’eau, le sucre, le sel et le beurre dans le bol à 100 ° sur mélange 3 sans accessoire.\nUne fois le beurre fondu, verser la farine. Bien dessécher la pâte pendant 3 minutes à 75 ° équipé du batteur souple.\nArrêter la température, continuer en vitesse 1 jusqu’à ce que la température soit en dessous de 60 °.\nAjouter les œufs un par un à la pâte jusqu’à ce que celle-ci soit lisse, souple et homogène.\nRemplir une poche munie d’une douille unie n°10 et plaquer les choux.\nCuire à 190° pendant 25 à 30 minutes.",
    "nom" : "Pâte à choux (Cooking Chef V2)",
    "tempsCuisson" : "30",
    "tempsPreparation" : "20",
    "video" : "",
    "categorie":"preparation"
  },
  {
    "description" : "Découvrez la recette de la pâte à pizza du restaurant Fonzarelli à Paris, une vraie pâte à pizza comme on la prépare en Italie...",
    "difficulte" : "facile",
    "image" : "http://static.750g.com/images/622-auto/535c86d8a270b359b5e743dcc00fc8b4/pate-a-pizza-fonzarelli.jpg",
    "ingredients" : "360 g de farine T45,270 g d'eau, 9 g de sel de guérande,4 g de levure fraîche de boulanger, 7 g d'huile d'olive",
    "instructions" : "Mettre la levure dans l'eau à température ambiante et mélanger.\nMettre l'eau et la levure dans le bol du pétrin et ajouter la farine, puis commencer à pétrir doucement pendant quelques minutes.\nUne fois que la boule est formé, accélérer le pétrissage, dés que la pâte devient élastique, réduire la vitesse.\nAjouter l'huile d'olive et accélérer à nouveau.\nAjouter le sel (dilué dans un peu d'eau) et continuer à pétrir.\nUne fois le bol bien sec, arrêter le pétrissage.\nDéposer la pâte dans un saladier et laisser reposé pendant 24h.\nEtaler la pâte sur un plan de travail fariné et laisser poussé pendant 30 mn.",
    "nom" : "Pâte à pizza",
    "tempsCuisson" : "15",
    "tempsPreparation" : "15",
    "video" : "https://www.youtube.com/watch?v=d0deh-SnUsA",
    "categorie":"plat"
  },
  {
    "description" : "Le gâteau basque façon espagnole",
    "difficulte" : "facile",
    "image" : "http://canalcocina.es/medias/_cache/zoom-1d508c705022461c30556dda631cc448-920-518.jpg",
    "ingredients" : "200 g de beurre, 200 g de sucre, 225 g de farine, 1 cc de levure, 1 zeste de citron, 2 oeufs, 1 jaune d'oeuf, Pour la crême :, 5 jaunes d'oeufs, 75 g de sucre, 20 g de farine, 10 g d'amidon, 1/2 l de lait",
    "instructions" : "Pour le gâteau, mélanger le beurre avec le sucre, la farine, la levure, le zeste, les œufs et le jaune.\nPétrir jusqu'à obtenir un mélange homogène et  laisser reposer.\nFaire une crème pâtissière, fouetter les jaunes de sucre, de farine et d'amidon dans un bol.\nInfuser une gousse de vanille dans le lait et laisser chauffer.\nAjouter le lait chaud au mélange et le détendre.\nRemettre le tout à feu moyen et porter à ébullition jusqu'à épaississement de la crème puis réserver.\nDans un moule à gâteau, verser la moitié de la pâte puis verser la crème tapissière et recouvrir du reste de la pâte.\nCuire au four pendant 30 à 45 mn à 180 °",
    "nom" : "Pastel Vasco",
    "tempsCuisson" : "35",
    "tempsPreparation" : "15",
    "video" : "https://www.youtube.com/watch?v=ijtWr-wAwX0",
    "categorie":"patisserie"
  },
  {
    "description" : "Délicieux muffins à la banane avec un coeur au chocolat blanc.",
    "difficulte" : "facile",
    "image" : "https://i.pinimg.com/originals/8c/8b/29/8c8b2986eb6ab93ee10e57a84d1966f6.jpg",
    "ingredients" : "340 g de farine,220 g de sucre en poudre,120 g de beurre, 4 bananes bien mûres,4 oeufs,10 cl de lait,2 sachets de levure chimique, 1 tablette de chocolat blanc",
    "instructions" : "Préchauffer le four à 180°.\nBattre les oeufs et le sucre.\nAjouter le beurre mou, puis la farine et la levure.\nVerser le lait et ajouter les bananes écrasées.\nVerser la préparation dans les moules à muffins.\nMettre un carré de chocolat blanc au centre.\nLaisser cuire pendant environ 25mn.",
    "nom" : "Muffins à la banane",
    "tempsCuisson" : "25mn",
    "tempsPreparation" : "15mn",
    "video" : "",
    "categorie":"patisserie"
  }
]

export default recettes;
